.TH DNETINFO 8 "March 30 2006" "DECnet utilities"

.SH NAME
dnetinfo \- DECnet Routing Information

dneigh \- DECnet Neighborhood Information

.SH SYNOPSIS
.B dnetinfo [OPTIONS...]

.B dneigh [OPTIONS...]

.SH DESCRIPTION
.PP
.B dneigh
shows the local DECnet neighbour table in a arp like format.

.PP
.B dnetinfo
is a a program that queries the dnroute daemon for it's current routes.
The output is very similar to the "SHOW NET/OLD" command on VMS.
.br
If dnroute is not running, or you don't have enough privilges to contact it
then it will fall back to dneigh behavor.

.SH OPTIONS
.TP
.I "\-n"
Don't resolve node numbers into names.

.TP
.I "\-h \-\-help"
Show a help text.

.TP
.I "\-\-dneigh"
Force dneigh behavor.

.TP
.I "\-\-dnetinfo"
Force dnetinfo behavor.

.SH SEE ALSO
.BR dnroute "(8), " ip "(8)"
