.TH CTERMD 8 "July 27 1998" "DECnet utilities"

.SH NAME
ctermd  \- CTERM services for Linux  

.SH SYNOPSIS
.B ctermd 
.br
[options]
.br
Options:
.br
[\-dvVh] [\-l logtype]
.SH DESCRIPTION
.PP
Allows remote users to connect as a terminal over DECnet.
.br
 
.br
This application implements the CTERM protocol over DECnet for allowing a 
remote DECnet host emulating a DEC VT100 terminal to connect to Linux.
.br

.br
Normally this daemon will be run from dnetd(8) rather than by hand.

.SH OPTIONS
.TP
.I "\-l"
Set logging options. The following are available:
.br
.B -lm
Log to /dev/mono. (only useful if you have my mono monitor driver or mdacon
and a second monitor)
.br
.B -le
Log to stderr. Use this for debugging or testing combined with
.B -d.
.br
.B -ls
Log to syslog(3). This is the default if no options are given.
.TP
.I "\-d"
Don't fork and run the background. Use this for debugging.
.TP
.I "\-v"
Verbose. The more of these there are the more verbose ctermd will be.
.TP
.I \-h \-?
Displays help for using the command.
.TP
.I \-V
Show the version of ctermd.

.SH EXAMPLES
.br
Starting the ctermd daemon/Connecting to linux from a VAX.
.br

.br
.PP
On Linux:

   # ctermd  

On the VAX:

   $ set host pclnx

   Ctermd Version 1.0.0
   DECnet for Linux

   login:

.br

.SH SEE ALSO
.BR dntype "(1), " dndir "(1), " dndel "(1), " dntask "(1), "
.BR dnetd "(8), " dnping "(1), " sethost "(1), " dnetd.conf (5)
