.TH DNCOPYNODES 8 "September 03 2008" "DECnet utilities"

.SH NAME
dncopynodes \- copy a list of nodes from a remote DEC system

.SH SYNOPSIS
.B dncopynodes <nodename> [ldif-dn]
.br
.SH DESCRIPTION
.PP
.br
This program will generate a decnet.conf file by contacting a remote
DECnet host (running VMS or RSX-11 probably) and doing the equivalent of
"NCP COPY KNOWN NODES". The resulting file can be copied over
the existing decnet.conf file if you like.
.br
You do need a fully-functioning DECnet system before using this command
but you don't need any nodes other than the executor defined in 
decnet.conf. 
.B dncopynodes 
will copy the executor information already there
into the new file.
.br
The program copies its output to standard output. It is strongly recommended
that you review it before replacing an existing /etc/decnet.conf file.
.br
The node name can also be a node address if you don't have any nodes defined in 
your existing decnet.conf.
.br
DO NOT attempt to redirect the output of 
.B dncopynodes 
directly into /etc/decnet.conf. It will fail and destroy your existing
configuration file! Send it to a temporary file and then copy it (see EXAMPLES)
.br
.br
.B dncopynodes 
can also create an LDIF file suitable for importing into an LDAP database. With
dnprogs 2.48 or later, DECnet programs can quiry this for node address information.
.SH EXAMPLE
# dncopynodes 3.34 > /tmp/decnet.conf
.br
# dncopynodes 3.34 dc=example,dc=com > /tmp/decnet.ldif
.br
# mv /tmp/decnet.conf /etc
.SH SEE ALSO
.BR decnet.conf "(5), " setether "(8)"


