.TH SETETHER 8 "March 01 2001" "DECnet utilities"

.SH NAME
setether \- Set the ethernet address for use with DECnet

.SH SYNOPSIS
.B setether <if> [<if>...]|all
[options]
.br
.SH DESCRIPTION
.PP
Set ethernet MAC address on ethernet adaptors
.br
 
.br
This script should be run at system startup. It will 
change the ethernet hardware (MAC) address of any or all ethernet interfaces to
match the DECnet node address. DECnet requires that the MAC address of all
ethernet adaptors running the protocol be set approriately.
If you do not run setether then you must change the ethernet address in some
other way for DECnet to work.
.br
By default no ethernet interfaces will have their MAC addresses changed by
setether, if you specify 
.B all
then all interfaces name eth* will be changed,
otherwise a list of interface names can be specified.
setether will enable (UP) all interfaces it changes the MAC addresses of.
.br
(2.4 only) The first interface specified on the command-line will also be made 
the default interface for DECnet operations (ie attempts to contact nodes not
in the neighbour table will be done over this interface).
.br
This script must be run with the interface inactive, it is normally run from 
/etc/init.d/decnet before TCP/IP starts up.
.br
.SH EXAMPLES
.br
set the MAC address of eth0.
.br
.PP
    # /sbin/setether eth0
.br
.br

set the MAC address of all ethernet interfaces
.br
.PP
    # /sbin/setether all
.br

.SH HELPFUL HINTS
If you have multiple ethernet cards on your system and they are connected
to the the same network you should
specify which one you want to use for DECnet communication on the setether
command line, otherwise they will both be given the same MAC address and this
is probably not what you want.
.br
Running DECnet on multiple ethernet interfaces only works under Linux 2.4. If you are
running Linux 2.2 then the interface name on the setether command line 
.B must
match the one in /etc/decnet.conf(5).
 
.SH SEE ALSO
.BR decnet.conf "(5), " dntype "(1), " dndir "(1), " dndel "(1), " dnetd "(8), " dnping "(1)" 


