.TH "dnetstat" "1" "September 2008" "dntools" "System Manager's Manual"

.SH NAME

dnetstat \- lists DECnet connections

.SH SYNOPSIS

dnetstat [\-n] [\-h|\-\-help]

.SH "DESCRIPTION"
\fBdnetstat\fR is a \fBnetstat\fR(8) like tool that displays current DECnet network connections.

.SH OPTIONS
.SS "\-n"
Show nodenames and numbered objects in as numerical addresses and don't resolve names.
.SS "\-\-help, \-h"
Prints a small help.

.SH SEE ALSO
\fBnetstat\fB(8).

.SH AUTHORS
This program is written by Philipp "ph3-der-loewe" Schafft <lion@lion.leolix.org>.
