.TH "node" "1" "August 2010" "dnprogs" "User Commands"

.SH NAME

node \- DECnet node name lookup tool

.SH SYNOPSIS

node {\-h|\-\-help}

node [\-v] [\-m] {nodename|nodeaddress}

.SH "DESCRIPTION"
\fBnode\fR is a tool that does name lookup of DECnet nodes.
It can lookup the node address from node name and node name
from node address.

.SH OPTIONS
.SS "\-v"
Be verbose. Prints useful (debug) messages.
.SS "\-\-help, \-h"
Prints a small help.

.SH SEE ALSO
\fBhost\fR(1).

.SH AUTHORS
This program is written by Philipp "ph3-der-loewe" Schafft <lion@lion.leolix.org>.
