.TH DNETNML 8 "September 5 2008" "DECnet utilities"

.SH NAME
dnetnml \- DECnet Network Management Listener
.SH SYNOPSIS
.B dnetnml
[options]
.br
Options:
.br
[\-dVh]
.SH DESCRIPTION
.PP
.B dnetnml
is a daemon that serves incoming management requests from remote systems, usually
NCP in the case of VMS and RSX. It is recommended that the daemon be run from dnetd
by adding the following line to /etc/dnetd.conf:
.br
NML            19         N         nobody       dnetnml
.br
 
.br
Currently it only serves a subset of information requests. These are (in NCP terms):
.br
SHOW ACTIVE NODES
.br
SHOW KNOWN NODES
.br
SHOW ADJACENT NODES
.br
SHOW EXEC CHAR
.br
SHOW KNOWN OBJECTS
.br
SHOW KNOWN LINKS
.br
SHOW ACTIVE CIRCUITS
.br
.br
Note that for SHOW KNOWN OBJECTS to work, /etc/dnetd.conf needs to be readable by
the daemon user (usually 'nobody') or it will return a Privilege Violation. There is no
sensitive data in this file so it's quite OK to set the permissions to 0644. Though 
this is not the default.
.SH OPTIONS
.TP
.I "\-d"
Don't fork and run the background. Use this for debugging.
.TP
.I "\-v"
Verbose. The more of these there are the more verbose dnetnml will be. Don't use 
more than one for normal operation because it will seriously impair 
performance.
.TP
.I \-h \-?
Displays help for using the command.
.TP
.I \-V
Show the version of dnetnml.
.SH BUGS
Probably lots, particularly as some of the functions are undocumented and I've had to reverse-engineer them.
SHOW KNOWN LINKS doesn't show quite the same information as VMS does. dnetnml relies on the information it
can get from /proc/net/decnet so it can't show load PIDs or processes unfortunately.
.SH SEE ALSO
.BR dnetd "(8), " dnetd.conf "(5)"
