.TH LIBDNET 3 "July 28, 1998"  "DECnet database functions" 
.SH NAME
libdnet \- DECnet database functions library
.SH SYNOPSIS

.B /usr/lib/libdnet.a
.br

.B /usr/lib/libdnet.so
.br

.SH DESCRIPTION

These are the DECnet database functions libraries. They are used 
to access and manipulate all the information contained in the 
decnet hosts configuration file:
.br
.B /etc/decnet.conf

.SH SEE ALSO

.BR dnet_addr (3),
.BR dnet_htoa (3),
.BR dnet_ntoa (3),
.BR dnet_conn (3),
.BR getnodeadd (3),
.BR getnodebyname (3),
.BR getnodebyaddr (3),
.br
.BR setnodeent (3)
